EscrowFPS.Mvc/Models/ErrorViewModel.cs
using System;

namespace EscrowFPS.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EscrowFPS.Mvc/Models/ExtendedLoanItem.cs
using System;

namespace EscrowFPS.Mvc.Models
{
    public class ExtendedLoanItem : Loan
    {
        public ExtendedLoanItem()
        {

        }

        public ExtendedLoanItem(Loan loan)
        {
            this.Id = loan.Id;
            this.Name = loan.Name;
            this.Rate = loan.Rate;
            this.Amount = loan.Amount;
            this.State = loan.State;
            this.Status = loan.Status;
            this.Product = loan.Product;
            this.LTV = loan.LTV;
            this.LockDays = loan.LockDays;
            this.Expires = loan.Expires;
        }

        public bool Selected { get; set; }

        public DateTime ExtendDate { get; set; }
    }
}

EscrowFPS.Mvc/Models/ExtendedLockViewModel.cs
using System.Collections.Generic;

namespace EscrowFPS.Mvc.Models
{
    public class ExtendedLockViewModel
    {
        public string LoanSearch { get; set; } = string.Empty;

        public string ErrorMessage { get; set; } = string.Empty;

        public List<ExtendedLoanItem> Loans { get; set; } = new List<ExtendedLoanItem>();
    }
}

EscrowFPS.Mvc/Models/Loan.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EscrowFPS.Mvc.Models
{
    public class Loan
    {
        [Required]
        public Guid Id { get; set; }
        public string LoanNumber { get; set; }
        public string Name { get; set; } 
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public string Product { get; set; }
        public string LTV { get; set; }
        public int LockDays { get; set; }
        public DateTime Expires { get; set; }

    }
}

EscrowFPS.Mvc/Models/UnlockLoanItem.cs
namespace EscrowFPS.Mvc.Models
{
    public class UnlockLoanItem : Loan
    {
        public UnlockLoanItem()
        {

        }

        public UnlockLoanItem(Loan l)
        {
            this.Id = l.Id;
            this.Name = l.Name;
            this.Rate = l.Rate;
            this.Amount = l.Amount;
            this.State = l.State;
            this.Status = l.Status;
            this.Product = l.Product;
            this.LTV = l.LTV;
            this.LockDays = l.LockDays;
            this.Expires = l.Expires;
        }

        public bool Selected { get; set; }
    }
}

EscrowFPS.Mvc/Models/UnlockViewModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace EscrowFPS.Mvc.Models
{
    public class UnlockViewModel
    {
        public string LoanSearch { get; set; } = string.Empty;

        [Description("Error Message")]
        public string ErrorMessage { get; set; } = string.Empty;

        public List<UnlockLoanItem> Loans { get; set; } = new List<UnlockLoanItem>();
    }
}

EscrowFPS.Mvc/Controllers/ExtendedLockController.cs
using EscrowFPS.Mvc.Models;
using EscrowFPS.Mvc.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace EscrowFPS.Mvc.Controllers
{
    public class ExtendedLockController : Controller
    {
        private ILoanService loanService;
        private ILogger<ExtendedLockController> log;

        public ExtendedLockController(ILoanService loanService, ILogger<ExtendedLockController> log)
        {
            this.loanService = loanService;
            this.log = log;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View("Index", new ExtendedLockViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Search(ExtendedLockViewModel state)
        {
            var parsedRequest = state.LoanSearch
                .Split(new[] { Environment.NewLine, " ", ",", ";" }, StringSplitOptions.RemoveEmptyEntries)
                .Distinct();
            var loans = await loanService.GetAsync(parsedRequest);
            state.Loans = loans.Select(x => new ExtendedLoanItem(x) { ExtendDate = x.Expires }).ToList();

            return View("Index", state);
        }

        [HttpPost]
        public async Task<IActionResult> ExtendedLock(ExtendedLockViewModel state)
        {
            var requests = state.Loans
                .Where(x => x.Selected && x.ExtendDate > x.Expires)
                .Select(x => new ExtendLockRequest
            {
                LoanId = x.Id,
                ExtendDate = x.ExtendDate,
            });

            var response = await loanService.ExtendLockAsync(requests);

            return View("Index", state);
        }


    }
}

EscrowFPS.Mvc/Controllers/HomeController.cs
using EscrowFPS.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EscrowFPS.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EscrowFPS.Mvc/Controllers/UnlockController.cs
using EscrowFPS.Mvc.Models;
using EscrowFPS.Mvc.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace EscrowFPS.Mvc.Controllers
{
    public class UnlockController: Controller
    {
        private ILoanService loanService;
        private ILogger<UnlockController> log;

        public UnlockController(ILoanService loanService, ILogger<UnlockController> log)
        {
            this.loanService = loanService;
            this.log = log;
        }

        public IActionResult Index()
        {
            return View("Index", new UnlockViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Search(UnlockViewModel state)
        {
            var parsedRequest = state.LoanSearch
                .Split(new[] { Environment.NewLine, " ", ",", ";" }, StringSplitOptions.RemoveEmptyEntries)
                .Distinct();

            var loans = await loanService.GetAsync(parsedRequest);
            state.Loans = loans.Select(x => new UnlockLoanItem(x)).ToList();

            return View("Index", state);
        }

        [HttpPost]
        public async Task<IActionResult> Unlock(UnlockViewModel state)
        {
            var requests = state.Loans
                .Where(x => x.Selected)
                .Select(x => new UnlockRequest
                {
                    LoanId = x.Id
                });

            var response = await loanService.Unlock(requests);
            return View("Index", state);
        }
    }
}

EscrowFPS.Mvc/Views/ExtendedLock/Index.cshtml
@model ExtendedLockViewModel
@{
    ViewData["Title"] = "Extended Lock";
}

<form asp-controller="ExtendedLock" asp-action="Search" method="post">
    <div class="form-group">
        <div class="col-6">
            <label asp-for="LoanSearch" class="control-label"></label>
            <textarea class="form-control" asp-for="LoanSearch" rows="5"></textarea>
        </div>
        <p />
        <div class="col-6">
            @if (string.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
            {
                <label asp-for="ErrorMessage"></label>
            }

        </div>
        <p />
        <div class="col-6">
            <input type="submit" value="Get Loans" class="btn btn-primary" />
        </div>
    </div>
</form>

@if (Model.Loans.Count > 0)
{
    <form asp-controller="ExtendedLock" asp-action="ExtendedLock" method="post">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th></th>
                                <th>
                                    <div class="form-check form-check-inline">
                                        <input class=" form-check-input" type="checkbox" id="chkSelectAll" onchange="selectAll()" />
                                    </div>
                                </th>
                                <th>Name</th>
                                <th>Rate</th>
                                <th>Amount</th>
                                <th>State</th>
                                <th>Status</th>
                                <th>Product</th>
                                <th>LTV</th>
                                <th>Lock Days</th>
                                <th>Expires</th>
                                <th>Extend</th>
                            </tr>
                        </thead>
                        @for (var i = 0; i < Model.Loans.Count; i++)
                        {
                            <tr>
                                <td><input type="hidden" asp-for="@Model.Loans[i].Id" /></td>
                                <td>
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" asp-for="@Model.Loans[i].Selected" class="form-check-input" />
                                    </div>
                                </td>
                                <td>@Model.Loans[i].Name</td>
                                <td>@Model.Loans[i].Rate</td>
                                <td>@Model.Loans[i].Amount</td>
                                <td>@Model.Loans[i].State</td>
                                <td>@Model.Loans[i].Status</td>
                                <td>@Model.Loans[i].Product</td>
                                <td>@Model.Loans[i].LTV</td>
                                <td>@Model.Loans[i].LockDays</td>
                                <td>@Model.Loans[i].Expires</td>
                                <td><input type="date" asp-for="@Model.Loans[i].ExtendDate" value="" /></td>
                            </tr>
                        }
                    </table>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-6">
                <input type="submit" value="Extend Lock" class="btn btn-primary" />
            </div>
        </div>

    </form>

    <script type="text/javascript">
        function selectAll() {
            let isChecked = document.getElementById("chkSelectAll");
            let loanSelectors = document.getElementsByClassName('loanSelector');
            for (let i = 0; i < loanSelectors.length; i++) {
                loanSelectors[i].checked = isChecked.checked;
            }
        }
    </script>
}

EscrowFPS.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Mr Cooper</h1>
    <h2>Escrow FPS</h2>
    <div class="container">
        <div class="row">
            <button asp-controller="Login" asp-action="Index" class="btn btn-primary">Login</button>
        </div>
        <div class="row">
            <button asp-controller="Unlock" asp-action="Index" class="btn btn-primary">Unlock</button>
        </div>
        <div class="row">
            <button asp-controller="ExtendedLock" asp-action="Index" class="btn btn-primary">Extended Lock</button>
        </div>
    </div>
    
    
    
</div>

EscrowFPS.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EscrowFPS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EscrowFPS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExtendedLock" asp-action="Index">Extended Lock</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Unlock" asp-action="Index">Unlock</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <label class="mr-sm-2" id="userName">User</label>
                    <button class="btn btn-outline-primary my-2 my-sm-0" asp-controller="login" asp-action="login">Login</button>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EscrowFPS.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EscrowFPS.Mvc/Views/Unlock/Index.cshtml
@model UnlockViewModel
@{
    ViewData["Title"] = "Unlock";
}

<form asp-controller="Unlock" asp-action="Search" method="post">
    <div class="form-group">
        <div class="col-6">
            <label asp-for="LoanSearch" class="control-label"></label>
            <textarea class="form-control" asp-for="LoanSearch" rows="5"></textarea>
        </div>
        <p />
        <div class="col-6">
            @if (string.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
            {
                <label asp-for="ErrorMessage"></label>
            }

        </div>
        <p />
        <div class="col-6">
            <input type="submit" value="Get Loans" class="btn btn-primary" />
        </div>
    </div>
</form>

@if (Model.Loans.Count > 0)
{
    <form asp-controller="Unlock" asp-action="Unlock" method="post">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="checkbox" id="chkSelectAll" onchange="selectAll()" />
                                    </div>
                                </th>
                                <th scope="col">Loan</th>
                                <th scope="col">Name</th>
                                <th scope="col">Rate</th>
                                <th scope="col">Amount</th>
                                <th scope="col">State</th>
                                <th scope="col">Status</th>
                                <th scope="col">Product</th>
                                <th scope="col">LTV</th>
                                <th scope="col">Expires</th>
                            </tr>
                        </thead>
                        @for (var i = 0; i < Model.Loans.Count; i++)
                        {
                            <tr>
                                <td><input type="hidden" asp-for="@Model.Loans[i].Id" /></td>
                                <td>
                                    <div class="form-check form-check-inline">
                                        <input type="checkbox" asp-for="@Model.Loans[i].Selected" class="loanSelector form-check-input" />
                                    </div>
                                </td>
                                <td>@Model.Loans[i].LoanNumber</td>
                                <td>@Model.Loans[i].Name</td>
                                <td>@Model.Loans[i].Rate</td>
                                <td>@Model.Loans[i].Amount</td>
                                <td>@Model.Loans[i].State</td>
                                <td>@Model.Loans[i].Status</td>
                                <td>@Model.Loans[i].Product</td>
                                <td>@Model.Loans[i].LTV</td>
                                <td>@Model.Loans[i].Expires</td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
        <div>

        </div>
        <div class="col-6">
            <input type="submit" value="Unlock" class="btn btn-primary" />
        </div>

    </form>

    <script type="text/javascript">
        function selectAll() {
            let isChecked = document.getElementById("chkSelectAll");
            let loanSelectors = document.getElementsByClassName('loanSelector');
            for (let i = 0; i < loanSelectors.length; i++) {
                loanSelectors[i].checked = isChecked.checked;
            }
        }
    </script>
}